server:
  port: 8080
  address: 127.0.0.1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.129:3306/learn_db?serverTimezone=GMT&generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Mysql2018*
  application:
    name: service-hi

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/